development:
  adapter: postgresql
  encoding: unicode
  database: flipkey_development
  pool: 5
  username: flipkey
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: flipkey_test
  pool: 5
  username: flipkey
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: flipkey_production
  pool: 5
  username: flipkey
  password: